application: app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: frontend/css
- url: /js
  static_dir: frontend/js
- url: /fonts
  static_dir: frontend/fonts
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest